language: php
php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
script: git diff --name-only $TRAVIS_COMMIT_RANGE | grep '\.php$' | xargs -n1 -P8 php -l | grep -v 'No syntax errors'; test $? -eq 1
