name: CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - run: composer phpcs
      - run: composer phpstan
