<?php
namespace Adminer;

class Plugins {
	/** @var true[] */ private static array $append = array('dumpFormat' => true, 'dumpOutput' => true, 'editRowPrint' => true, 'editFunctions' => true, 'config' => true); // these hooks expect the value to be appended to the result

	/** @var list<object> @visibility protected(set) */ public array $plugins;
	/** @var string[] @visibility protected(set) */ public array $drivers = array(); // [id => name] of drivers registered by plugins
	/** @var string[] @visibility protected(set) */ public array $driverFiles = array(); // [id => filename] of files which registered a driver
	/** @visibility protected(set) */ public string $error = ''; // HTML
	/** @var list<object>[] */ private array $hooks = array();

	/** Register plugins
	* @param ?list<object> $plugins object instances or null to autoload plugins from adminer-plugins/
	*/
	function __construct(?array $plugins) {
		$drivers = SqlDriver::$drivers; // bundled drivers, plugin drivers are registered below
		if ($plugins === null) {
			$plugins = array();
			$basename = "adminer-plugins";
			if (is_dir($basename)) {
				foreach (glob("$basename/*.php") as $filename) {
					$file_drivers = SqlDriver::$drivers;
					$this->includeOnce($filename);
					foreach (array_diff_key(SqlDriver::$drivers, $file_drivers) as $id => $name) {
						$this->driverFiles[$id] = $filename;
					}
				}
			}
			$help = " href='https://www.adminer.org/plugins/#use'" . target_blank();
			if (file_exists("$basename.php")) {
				$include = $this->includeOnce("$basename.php"); // example: return array(new AdminerLoginOtp($secret));
				if (is_array($include)) {
					foreach ($include as $plugin) {
						$plugins[get_class($plugin)] = $plugin;
					}
				} else {
					$this->error .= lang('%s must <a%s>return an array</a>.', "<b>$basename.php</b>", $help) . "<br>";
				}
			}
			foreach (get_declared_classes() as $class) {
				if (!$plugins[$class] && (preg_match('~^Adminer\w~i', $class) || is_subclass_of($class, 'Adminer\Plugin'))) {
					// we need to use reflection because PHP 7.1 throws ArgumentCountError for missing arguments but older versions issue a warning
					$reflection = new \ReflectionClass($class);
					$constructor = $reflection->getConstructor();
					if ($constructor && $constructor->getNumberOfRequiredParameters()) {
						$this->error .= lang('<a%s>Configure</a> %s in %s.', $help, "<b>$class</b>", "<b>$basename.php</b>") . "<br>";
					} else {
						$plugins[$class] = new $class;
					}
				}
			}
		}
		$this->drivers = array_diff_key(SqlDriver::$drivers, $drivers);
		$this->plugins = $plugins;

		$adminer = new Adminer;
		$plugins[] = $adminer;
		$reflection = new \ReflectionObject($adminer);
		foreach ($reflection->getMethods() as $method) {
			foreach ($plugins as $plugin) {
				$name = $method->getName();
				if (method_exists($plugin, $name)) {
					$this->hooks[$name][] = $plugin;
				}
			}
		}
	}

	/** Separate function to not overwrite local variables
	* @return array<object>|true
	*/
	function includeOnce(string $filename) {
		return include_once "./$filename";
	}

	/** Get checksums of files with loaded plugins, ignoring line ends and translations
	* @return string[] plugin name in key, hex crc32 in value
	*/
	function checksums(): array {
		$filenames = array_values($this->driverFiles);
		foreach ($this->plugins as $plugin) {
			$filenames[] = (new \ReflectionObject($plugin))->getFileName();
		}
		$return = array();
		foreach ($filenames as $filename) {
			// this transformation is matched by checksums.php generating officialChecksums()
			$file = str_replace("\r", "", file_get_contents($filename));
			$file = preg_replace('~\n\tprotected \$translations = array\(.*?\n\t\);~s', '', $file);
			$return[basename($filename, '.php')] = dechex(crc32($file));
		}
		return $return;
	}

	/** Get checksums of official plugins shipped with this Adminer version; regenerated by checksums.php
	* @return string[] plugin name in key, hex crc32
	*/
	static function officialChecksums(): array {
		return array(
			'adminer.js' => 'a0599090',
			'backward-keys' => '82e2dd97',
			'before-unload' => 'df99c65e',
			'config' => '3685e6ed',
			'dark-switcher' => '6de2ef40',
			'database-hide' => '90c6c0dc',
			'designs' => '6423f7de',
			'dump-alter' => 'd078b2db',
			'dump-bz2' => 'f0d0e336',
			'dump-date' => 'adc7f1c7',
			'dump-json' => '7c24133b',
			'dump-xml' => 'f66f5942',
			'dump-zip' => '93817d96',
			'edit-foreign' => '177c3414',
			'edit-textarea' => 'a24c3cc',
			'editor-setup' => 'a7dc3a37',
			'editor-views' => '5c12b185',
			'enum-option' => 'd83d3f82',
			'file-upload' => '235eaa7a',
			'foreign-system' => 'ebb4c654',
			'frames' => 'b0e1d11a',
			'highlight-codemirror' => 'f1a34275',
			'highlight-monaco' => 'ae191d99',
			'highlight-prism' => '2a210fee',
			'login-ip' => '3d1521bf',
			'login-otp' => '62c517c0',
			'login-password-less' => 'a0484549',
			'login-reverse-proxy' => '7bb63f11',
			'login-servers' => '5d669a86',
			'login-ssl' => 'f8f90fe4',
			'login-table' => 'c3c83442',
			'menu-links' => '48973237',
			'row-numbers' => 'eec8698c',
			'select-email' => 'ac60f38b',
			'slugify' => 'c978390e',
			'sql-gemini' => '2368f8b3',
			'sql-log' => 'b4355039',
			'table-indexes-structure' => 'd1df9697',
			'table-structure' => '7a4e9b0',
			'tables-filter' => 'dde1e2d6',
			'timeout' => '90597366',
			'version-github' => 'c9dbb700',
			'version-noverify' => '966937e9',
			'clickhouse' => '11c4d83c',
			'elastic' => '1894f81f',
			'firebird' => '438fd55d',
			'igdb' => '141eb139',
			'imap' => '71c6f9e6',
			'mongo' => 'a5132cd7',
			'redis' => 'cae5931e',
			'simpledb' => '38028120',
		);
	}

	/**
	* @param literal-string $name
	* @param mixed[] $params
	* @return mixed
	*/
	function __call(string $name, array $params) {
		$args = array();
		foreach ($params as $key => $val) {
			// some plugins accept params by reference - we don't need to propagate it outside, just to the other plugins
			$args[] = &$params[$key];
		}
		$return = null;
		foreach ($this->hooks[$name] as $plugin) {
			$value = call_user_func_array(array($plugin, $name), $args);
			if ($value !== null) {
				if (!self::$append[$name]) { // non-null value from non-appending method short-circuits the other plugins
					return $value;
				}
				$return = $value + (array) $return;
			}
		}
		return $return;
	}
}
